In [1]:
import pandas as pd
import requests

baseUrl = "https://tradingeconomics.com/"

# Define user-agent header to trick website into thinking we're a genuine user
headers = {
    'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36'
}

def teMarkets(datasets):
    """
        Retrieves market data from www.tradingeconomics.com, given an input target dataset.
        Note the data is extracted from the website's HTML, not the actual API, so may be prone to breaking.

        Inputs
        * list of strings representing the target market datasets, eg. ['bonds', 'stocks']
        * strings must be one of the following options:
            - 'bonds'
            - 'commodities'
            - 'crypto'
            - 'currencies'
            - 'stocks'

        Returns a dictionary where the keys are equal to the input strings and the values are either a
        dataframe object if successful or a string of the error code/message if not.

        Note
        * When calling bonds, the data is for government 10Y notes.
        * Duplicates are removed.
    """

    # Initialise the return dictionary
    returnDict = {}

    # Initialise a session object
    session = requests.Session()

    # If statements which append to the return dictionary if True
    if "bonds" in datasets:
        url = "{}{}".format(baseUrl, "bonds")
        request = requests.get(url, headers=headers)
        if request.status_code == 200:
            try:
                tables = pd.read_html(request.text)
                for index, table in enumerate(tables):
                    region = table.columns[1]
                    table = table.rename(columns={table.columns[0]:"Region", region: "Bond"})
                    table["Bond"] = table["Bond"].apply(lambda x: "{} 10Y".format(x))
                    table["Region"] = [region for i in range(len(table))]
                    
                    if index == 0:
                        bondsDf = table
                    else:
                        bondsDf = pd.concat([bondsDf, table])
                bondsDf = bondsDf.drop_duplicates(subset="Bond", keep='last', ignore_index=True)
                returnDict["bonds"] = bondsDf

            except:
                returnDict["bonds"] = "Successful request but error loading data..."
        else:
            returnDict["bonds"] = "Request error: {}".format(request.status_code)

    if "commodities" in datasets:
        url = "{}{}".format(baseUrl, "commodities")
        request = requests.get(url, headers=headers)
        if request.status_code == 200:
            try:
                tables = pd.read_html(request.text)
                for index, table in enumerate(tables):
                    category = table.columns[0]
                    table["Category"] = [category for i in range(len(table))]
                    table = table.rename(columns={category: "Commodity"})
                    
                    if index == 0:
                        commodityDf = table
                    else:
                        commodityDf = pd.concat([commodityDf, table])
                commodityDf = commodityDf.drop_duplicates(subset="Commodity", keep="last", ignore_index=True)
                returnDict["commodities"] = commodityDf
            except:
                returnDict["commodities"] = "Successful request but error loading data"
        else:
            returnDict["commodities"] = "Request error: {}".format(request.status_code)

    if "crypto" in datasets:
        url = "{}{}".format(baseUrl, "crypto")
        request = session.get(url, headers=headers)
        if request.status_code == 200:
            try:
                tables = pd.read_html(request.text)
                for index, table in enumerate(tables):
                    category = table.columns[0]
                    table["Category"] = [category for i in range(len(table))]
                    table = table.rename(columns={table.columns[0]: "Product"})

                    if index == 0:
                        cryptoDf = table
                    else:
                        cryptoDf = pd.concat([cryptoDf, table], ignore_index=True)
                returnDict["crypto"] = cryptoDf
            except:
                returnDict["crypto"] = "Sucessful request but error loading data..."
        else:
            returnDict["crypto"] = "Request error: {}".format(request.status_code)

    if "currencies" in datasets:
        url = "{}{}".format(baseUrl, "currencies")
        request = requests.get(url, headers=headers)
        if request.status_code == 200:
            try:
                tables = pd.read_html(request.text)
                for index, table in enumerate(tables):
                    region = table.columns[1]
                    table = table.rename(columns={table.columns[0]: "Region", table.columns[1]: "CurrencyPair"})
                    table.Region = [region for i in range(len(table))]

                    if index == 0:
                        currencyDf = table
                    else:
                        currencyDf = pd.concat([currencyDf, table])
                currencyDf = currencyDf.drop_duplicates(subset="CurrencyPair", keep='last', ignore_index=True)
                returnDict["currencies"] = currencyDf
            except:
                returnDict["currencies"] = "Successful request but error loading data..."
        else:
            returnDict["currencies"] = "Request error: {}".format(request.status_code)
 
    if "stocks" in datasets:
        url = "{}{}".format(baseUrl, "stocks")
        request = requests.get(url, headers=headers)
        if request.status_code == 200:
            try:
                tables = pd.read_html(request.text)
                for index, table in enumerate(tables):
                    region = table.columns[1]
                    table = table.rename(columns={table.columns[0]: "Region", table.columns[1]: "Index"})
                    table.Region = [region for i in range(len(table))]

                    if index == 0:
                        stocksDf = table
                    else:
                        stocksDf = pd.concat([stocksDf, table])
                stocksDf = stocksDf.drop_duplicates(subset="Index", keep='last', ignore_index=True)
                returnDict["stocks"] = stocksDf
            except:
                returnDict["stocks"] = "Successful request but error loading data..."
        else:
            returnDict["stocks"] = "Request error: {}".format(request.status_code)
    return returnDict

# EXAMPLE
if __name__ == "__main__":
    data = teMarkets(["crypto", "stocks","commodities"])

C:\Users\HP SUPPORT\AppData\Roaming\Python\Python39\site-packages\pandas\core\computation\expressions.py:21: UserWarning: Pandas requires version '2.8.4' or newer of 'numexpr' (version '2.8.3' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
C:\Users\HP SUPPORT\AppData\Roaming\Python\Python39\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (
C:\Users\HP SUPPORT\AppData\Local\Temp\ipykernel_2732\1683100861.py:69: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(request.text)
C:\Users\HP SUPPORT\AppData\Local\Temp\ipykernel_2732\1683100861.py:91: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(request.text)
C:\Users\HP SUPPORT\AppData\Local\Temp\ipykernel_2732\1683100861.py:134: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(request.text)

In [2]:
data["crypto"].head()

,Product,Price,Day,%,Weekly,Monthly,YoY,MarketCap,Date,Category
0,Bitcoin,64206.00000,139.0000,0.22%,0.53%,-7.38%,121.77%,"$1,214,280M",May/06,Crypto
1,Ether,3148.70000,11.0000,0.35%,-2.19%,-7.43%,63.94%,"$374,373M",May/06,Crypto
2,Binance,591.70000,1.0000,0.17%,-0.54%,1.72%,83.13%,"$96,140M",May/06,Crypto
3,Cardano,0.45795,0.0005,-0.10%,0.10%,-22.15%,20.70%,"$15,428M",May/06,Crypto
4,Solana,147.39000,1.6355,1.12%,7.09%,-17.90%,562.60%,"$45,456M",May/06,Crypto

In [3]:
data["stocks"].head()

,Region,Index,Price,Day,%,Weekly,Monthly,YoY,Date,Unnamed: 9
0,Europe,GB100,8213.0,41.0,0.51%,0.91%,2.98%,6.63%,May/03,NaN
1,Europe,DE40,18068.0,67.0,0.37%,-0.28%,-1.37%,13.26%,May/06,NaN
2,Europe,FR40,7958.0,43.0,0.54%,-1.62%,-2.38%,8.40%,May/03,NaN
3,Europe,IT40,33629.0,107.0,-0.32%,-1.81%,-2.40%,26.09%,May/03,NaN
4,Europe,ES35,10855.0,17.0,-0.16%,-2.69%,-2.13%,20.03%,May/03,NaN

In [4]:
data["commodities"].head()

,Commodity,Price,Day,%,Weekly,Monthly,YoY,Date,Category
0,Crude Oil USD/Bbl,78.3890,0.3990,0.51%,-5.24%,-9.30%,7.66%,May/06,Energy
1,Brent USD/Bbl,83.2430,0.4230,0.51%,-4.54%,-7.90%,8.09%,May/06,Energy
2,Natural gas USD/MMBtu,2.1538,0.0038,0.18%,6.10%,15.95%,-3.76%,May/06,Energy
3,Gasoline USD/Gal,2.5521,0.0047,-0.18%,-7.22%,-7.20%,3.68%,May/06,Energy
4,Heating Oil USD/Gal,2.4406,0.0006,0.02%,-3.75%,-10.56%,2.65%,May/06,Energy

# EVENTS

https://docs.tradingeconomics.com/economic_calendar/snapshot/

In [5]:
import requests
api_key = '52907c12211a4c4:tb36co5d1u5rv2l'
url = f'https://api.tradingeconomics.com/calendar?c={api_key}'
data = requests.get(url).json()
print(data)


import tradingeconomics as te
te.login('52907c12211a4c4:tb36co5d1u5rv2l')
te.getCalendarData()

[{'CalendarId': '341836', 'Date': '2024-05-06T00:00:00', 'Country': 'Thailand', 'Category': 'Holidays', 'Event': 'Coronation Day', 'Reference': '', 'ReferenceDate': None, 'Source': '', 'SourceURL': '', 'Actual': '', 'Previous': '', 'Forecast': '', 'TEForecast': '', 'URL': '/thailand/holidays', 'DateSpan': '0', 'Importance': 1, 'LastUpdate': '2023-11-22T12:30:03.12', 'Revised': '', 'Currency': '', 'Unit': '', 'Ticker': 'HOLIDAYSTHAILAND', 'Symbol': ''}, {'CalendarId': '350787', 'Date': '2024-05-06T06:30:00', 'Country': 'Sweden', 'Category': 'Services PMI', 'Event': 'Services PMI', 'Reference': 'Apr', 'ReferenceDate': '2024-04-30T00:00:00', 'Source': 'Swedbank', 'SourceURL': 'https://www.swedbank.com/', 'Actual': '', 'Previous': '53.9', 'Forecast': '', 'TEForecast': '53.2', 'URL': '/sweden/services-pmi', 'DateSpan': '0', 'Importance': 1, 'LastUpdate': '2024-05-03T07:15:54.15', 'Revised': '', 'Currency': '', 'Unit': '', 'Ticker': 'SWEDENSERPMI', 'Symbol': 'SWEDENSERPMI'}, {'CalendarId': '350914', 'Date': '2024-05-06T07:30:00', 'Country': 'Thailand', 'Category': 'Business Confidence', 'Event': 'Business Confidence', 'Reference': 'Apr', 'ReferenceDate': '2024-04-30T00:00:00', 'Source': 'Bank of Thailand', 'SourceURL': 'https://www.bot.or.th', 'Actual': '', 'Previous': '49.6', 'Forecast': '', 'TEForecast': '49.8', 'URL': '/thailand/business-confidence', 'DateSpan': '0', 'Importance': 1, 'LastUpdate': '2024-04-10T10:42:30.757', 'Revised': '', 'Currency': '', 'Unit': '', 'Ticker': 'THAILANDBC', 'Symbol': 'ThailandBC'}, {'CalendarId': '350919', 'Date': '2024-05-06T07:30:00', 'Country': 'Thailand', 'Category': 'Foreign Exchange Reserves', 'Event': 'Foreign Exchange Reserves', 'Reference': 'Apr', 'ReferenceDate': '2024-04-30T00:00:00', 'Source': 'Bank of Thailand', 'SourceURL': 'https://www.bot.or.th', 'Actual': '', 'Previous': '$223.4B', 'Forecast': '', 'TEForecast': '', 'URL': '/thailand/foreign-exchange-reserves', 'DateSpan': '0', 'Importance': 1, 'LastUpdate': '2024-04-12T07:31:00.88', 'Revised': '', 'Currency': '$', 'Unit': 'B', 'Ticker': 'THAILANDFOREXCRES', 'Symbol': 'THAILANDFOREXCRES'}, {'CalendarId': '350842', 'Date': '2024-05-07T12:00:00', 'Country': 'Mexico', 'Category': 'Consumer Confidence', 'Event': 'Consumer Confidence', 'Reference': 'Apr', 'ReferenceDate': '2024-04-30T00:00:00', 'Source': 'Instituto Nacional de Estadística y Geografía (INEGI)', 'SourceURL': 'https://www.inegi.org.mx/', 'Actual': '', 'Previous': '47.3', 'Forecast': '', 'TEForecast': '', 'URL': '/mexico/consumer-confidence', 'DateSpan': '0', 'Importance': 2, 'LastUpdate': '2024-04-05T09:00:23.557', 'Revised': '', 'Currency': '', 'Unit': '', 'Ticker': 'MXCFCONF', 'Symbol': 'MXCFCONF'}, {'CalendarId': '351049', 'Date': '2024-05-07T12:00:00', 'Country': 'Mexico', 'Category': 'Car Production', 'Event': 'Auto Production YoY', 'Reference': 'Apr', 'ReferenceDate': '2024-04-30T00:00:00', 'Source': 'Instituto Nacional de Estadística y Geografía (INEGI)', 'SourceURL': 'https://www.inegi.org.mx', 'Actual': '', 'Previous': '-12.8%', 'Forecast': '', 'TEForecast': '', 'URL': '/mexico/car-production', 'DateSpan': '0', 'Importance': 1, 'LastUpdate': '2024-04-05T12:03:37.44', 'Revised': '', 'Currency': '', 'Unit': '%', 'Ticker': 'MEXICOCARPRO', 'Symbol': 'MEXICOCARPRO'}, {'CalendarId': '351050', 'Date': '2024-05-07T12:00:00', 'Country': 'Mexico', 'Category': 'Auto Exports', 'Event': 'Auto Exports YoY', 'Reference': 'Apr', 'ReferenceDate': '2024-04-30T00:00:00', 'Source': 'Instituto Nacional de Estadística y Geografía (INEGI)', 'SourceURL': 'https://www.inegi.org.mx/', 'Actual': '', 'Previous': '4.9%', 'Forecast': '', 'TEForecast': '', 'URL': '/mexico/auto-exports', 'DateSpan': '0', 'Importance': 1, 'LastUpdate': '2024-04-05T12:03:42.943', 'Revised': '', 'Currency': '', 'Unit': '%', 'Ticker': 'MEXICOAUTEXP', 'Symbol': 'MEXICOAUTEXP'}, {'CalendarId': '342999', 'Date': '2024-05-07T15:00:00', 'Country': 'New Zealand', 'Category': 'Global Dairy Trade Price Index', 'Event': 'Global Dairy Trade Price Index', 'Reference': 'May/07', 'ReferenceDate': '2024-05-07T00:00:00', 'Source': 'GlobalDairyTrade', 'SourceURL': 'https://www.globaldairytrade.info/', 'Actual': '', 'Previous': '0.1%', 'Forecast': '', 'TEForecast': '', 'URL': '/new-zealand/global-dairy-trade-price-index', 'DateSpan': '1', 'Importance': 1, 'LastUpdate': '2024-04-16T15:23:12.837', 'Revised': '', 'Currency': '', 'Unit': '%', 'Ticker': 'NEWZEALANGDTPI', 'Symbol': 'NEWZEALANGDTPI'}, {'CalendarId': '364148', 'Date': '2024-05-08T06:00:00', 'Country': 'Sweden', 'Category': 'House Price Index MoM', 'Event': 'House Price Index MoM', 'Reference': 'Apr', 'ReferenceDate': '2024-04-30T00:00:00', 'Source': 'Statistics Sweden', 'SourceURL': 'https://www.scb.se/', 'Actual': '', 'Previous': '-2%', 'Forecast': '', 'TEForecast': '-1.0%', 'URL': '/sweden/house-price-index-mom', 'DateSpan': '0', 'Importance': 1, 'LastUpdate': '2024-04-26T14:29:11.14', 'Revised': '', 'Currency': '', 'Unit': '%', 'Ticker': 'SWEHPIM', 'Symbol': 'SWEHPIM'}, {'CalendarId': '339360', 'Date': '2024-05-08T07:30:00', 'Country': 'Sweden', 'Category': 'Interest Rate', 'Event': 'Riksbank Rate Decision', 'Reference': '', 'ReferenceDate': '2024-05-08T00:00:00', 'Source': 'Sveriges Riksbank', 'SourceURL': 'https://www.riksbank.se/', 'Actual': '', 'Previous': '4%', 'Forecast': '', 'TEForecast': '4%', 'URL': '/sweden/interest-rate', 'DateSpan': '0', 'Importance': 2, 'LastUpdate': '2024-04-26T14:28:57.28', 'Revised': '', 'Currency': '', 'Unit': '%', 'Ticker': 'SWRRATEI', 'Symbol': 'SWRRATEI'}]

[{'CalendarId': '339360',
  'Date': '2024-05-08T07:30:00',
  'Country': 'Sweden',
  'Category': 'Interest Rate',
  'Event': 'Riksbank Rate Decision',
  'Reference': '',
  'ReferenceDate': '2024-05-08T00:00:00',
  'Source': 'Sveriges Riksbank',
  'SourceURL': 'https://www.riksbank.se/',
  'Actual': '',
  'Previous': '4%',
  'Forecast': '',
  'TEForecast': '4%',
  'URL': '/sweden/interest-rate',
  'DateSpan': '0',
  'Importance': 2,
  'LastUpdate': '2024-04-26T14:28:57.28',
  'Revised': '',
  'Currency': '',
  'Unit': '%',
  'Ticker': 'SWRRATEI',
  'Symbol': 'SWRRATEI'},
 {'CalendarId': '364148',
  'Date': '2024-05-08T06:00:00',
  'Country': 'Sweden',
  'Category': 'House Price Index MoM',
  'Event': 'House Price Index MoM',
  'Reference': 'Apr',
  'ReferenceDate': '2024-04-30T00:00:00',
  'Source': 'Statistics Sweden',
  'SourceURL': 'https://www.scb.se/',
  'Actual': '',
  'Previous': '-2%',
  'Forecast': '',
  'TEForecast': '-1.0%',
  'URL': '/sweden/house-price-index-mom',
  'DateSpan': '0',
  'Importance': 1,
  'LastUpdate': '2024-04-26T14:29:11.14',
  'Revised': '',
  'Currency': '',
  'Unit': '%',
  'Ticker': 'SWEHPIM',
  'Symbol': 'SWEHPIM'},
 {'CalendarId': '342999',
  'Date': '2024-05-07T15:00:00',
  'Country': 'New Zealand',
  'Category': 'Global Dairy Trade Price Index',
  'Event': 'Global Dairy Trade Price Index',
  'Reference': 'May/07',
  'ReferenceDate': '2024-05-07T00:00:00',
  'Source': 'GlobalDairyTrade',
  'SourceURL': 'https://www.globaldairytrade.info/',
  'Actual': '',
  'Previous': '0.1%',
  'Forecast': '',
  'TEForecast': '',
  'URL': '/new-zealand/global-dairy-trade-price-index',
  'DateSpan': '1',
  'Importance': 1,
  'LastUpdate': '2024-04-16T15:23:12.837',
  'Revised': '',
  'Currency': '',
  'Unit': '%',
  'Ticker': 'NEWZEALANGDTPI',
  'Symbol': 'NEWZEALANGDTPI'},
 {'CalendarId': '351050',
  'Date': '2024-05-07T12:00:00',
  'Country': 'Mexico',
  'Category': 'Auto Exports',
  'Event': 'Auto Exports YoY',
  'Reference': 'Apr',
  'ReferenceDate': '2024-04-30T00:00:00',
  'Source': 'Instituto Nacional de Estadística y Geografía (INEGI)',
  'SourceURL': 'https://www.inegi.org.mx/',
  'Actual': '',
  'Previous': '4.9%',
  'Forecast': '',
  'TEForecast': '',
  'URL': '/mexico/auto-exports',
  'DateSpan': '0',
  'Importance': 1,
  'LastUpdate': '2024-04-05T12:03:42.943',
  'Revised': '',
  'Currency': '',
  'Unit': '%',
  'Ticker': 'MEXICOAUTEXP',
  'Symbol': 'MEXICOAUTEXP'},
 {'CalendarId': '351049',
  'Date': '2024-05-07T12:00:00',
  'Country': 'Mexico',
  'Category': 'Car Production',
  'Event': 'Auto Production YoY',
  'Reference': 'Apr',
  'ReferenceDate': '2024-04-30T00:00:00',
  'Source': 'Instituto Nacional de Estadística y Geografía (INEGI)',
  'SourceURL': 'https://www.inegi.org.mx',
  'Actual': '',
  'Previous': '-12.8%',
  'Forecast': '',
  'TEForecast': '',
  'URL': '/mexico/car-production',
  'DateSpan': '0',
  'Importance': 1,
  'LastUpdate': '2024-04-05T12:03:37.44',
  'Revised': '',
  'Currency': '',
  'Unit': '%',
  'Ticker': 'MEXICOCARPRO',
  'Symbol': 'MEXICOCARPRO'},
 {'CalendarId': '350842',
  'Date': '2024-05-07T12:00:00',
  'Country': 'Mexico',
  'Category': 'Consumer Confidence',
  'Event': 'Consumer Confidence',
  'Reference': 'Apr',
  'ReferenceDate': '2024-04-30T00:00:00',
  'Source': 'Instituto Nacional de Estadística y Geografía (INEGI)',
  'SourceURL': 'https://www.inegi.org.mx/',
  'Actual': '',
  'Previous': '47.3',
  'Forecast': '',
  'TEForecast': '',
  'URL': '/mexico/consumer-confidence',
  'DateSpan': '0',
  'Importance': 2,
  'LastUpdate': '2024-04-05T09:00:23.557',
  'Revised': '',
  'Currency': '',
  'Unit': '',
  'Ticker': 'MXCFCONF',
  'Symbol': 'MXCFCONF'},
 {'CalendarId': '350919',
  'Date': '2024-05-06T07:30:00',
  'Country': 'Thailand',
  'Category': 'Foreign Exchange Reserves',
  'Event': 'Foreign Exchange Reserves',
  'Reference': 'Apr',
  'ReferenceDate': '2024-04-30T00:00:00',
  'Source': 'Bank of Thailand',
  'SourceURL': 'https://www.bot.or.th',
  'Actual': '',
  'Previous': '$223.4B',
  'Forecast': '',
  'TEForecast': '',
  'URL': '/thailand/foreign-exchange-reserves',
  'DateSpan': '0',
  'Importance': 1,
  'LastUpdate': '2024-04-12T07:31:00.88',
  'Revised': '',
  'Currency': '$',
  'Unit': 'B',
  'Ticker': 'THAILANDFOREXCRES',
  'Symbol': 'THAILANDFOREXCRES'},
 {'CalendarId': '350914',
  'Date': '2024-05-06T07:30:00',
  'Country': 'Thailand',
  'Category': 'Business Confidence',
  'Event': 'Business Confidence',
  'Reference': 'Apr',
  'ReferenceDate': '2024-04-30T00:00:00',
  'Source': 'Bank of Thailand',
  'SourceURL': 'https://www.bot.or.th',
  'Actual': '',
  'Previous': '49.6',
  'Forecast': '',
  'TEForecast': '49.8',
  'URL': '/thailand/business-confidence',
  'DateSpan': '0',
  'Importance': 1,
  'LastUpdate': '2024-04-10T10:42:30.757',
  'Revised': '',
  'Currency': '',
  'Unit': '',
  'Ticker': 'THAILANDBC',
  'Symbol': 'ThailandBC'},
 {'CalendarId': '350787',
  'Date': '2024-05-06T06:30:00',
  'Country': 'Sweden',
  'Category': 'Services PMI',
  'Event': 'Services PMI',
  'Reference': 'Apr',
  'ReferenceDate': '2024-04-30T00:00:00',
  'Source': 'Swedbank',
  'SourceURL': 'https://www.swedbank.com/',
  'Actual': '',
  'Previous': '53.9',
  'Forecast': '',
  'TEForecast': '53.2',
  'URL': '/sweden/services-pmi',
  'DateSpan': '0',
  'Importance': 1,
  'LastUpdate': '2024-05-03T07:15:54.15',
  'Revised': '',
  'Currency': '',
  'Unit': '',
  'Ticker': 'SWEDENSERPMI',
  'Symbol': 'SWEDENSERPMI'},
 {'CalendarId': '341836',
  'Date': '2024-05-06T00:00:00',
  'Country': 'Thailand',
  'Category': 'Holidays',
  'Event': 'Coronation Day',
  'Reference': '',
  'ReferenceDate': None,
  'Source': '',
  'SourceURL': '',
  'Actual': '',
  'Previous': '',
  'Forecast': '',
  'TEForecast': '',
  'URL': '/thailand/holidays',
  'DateSpan': '0',
  'Importance': 1,
  'LastUpdate': '2023-11-22T12:30:03.12',
  'Revised': '',
  'Currency': '',
  'Unit': '',
  'Ticker': 'HOLIDAYSTHAILAND',
  'Symbol': ''}]

In [6]:
# GDP

In [9]:
# To get historical data by specific country, indicator, start date and end date
mydata = te.getHistoricalData(country='mexico',  indicator='gdp', initDate='2015-01-01', endDate='2015-12-31', output_type='df')
print(mydata)
print("===============================================================================================================")

  Country Category             DateTime    Value Frequency  \
0  Mexico      GDP  2022-12-31T00:00:00  1465.85    Yearly
1  Mexico      GDP  2021-12-31T00:00:00  1312.56    Yearly
2  Mexico      GDP  2020-12-31T00:00:00  1120.74    Yearly

  HistoricalDataSymbol           LastUpdate
0             WGDPMEXI  2024-01-02T15:00:00
1             WGDPMEXI  2024-01-02T15:00:00
2             WGDPMEXI  2024-01-02T15:00:00
===============================================================================================================

In [8]:
import pandas as pd
import tradingeconomics as te
te.login('guest:guest')

## Without a client key only a small sample of data will be given.

## Putting country name or indicator name in square brackets [] will result, by default
## in the dictionary type for several countries and indicators.
## EXE: country=['mexico', 'sweden']

## With no output_type defined, the result will be of the dictionary type.
## Use output_type='df' to display in pandas dataframe. 


# To get historical data by specific country, indicator, start date and end date
mydata = te.getHistoricalData(country='china',  indicator='gdp', initDate='2015-01-01', endDate='2015-12-31', output_type='df')
print(mydata)
print("===============================================================================================================")


# # To get a list of discontinued indicators series with multiple countries.
# mydata = te.getDiscontinuedIndicator(country=['united states', 'china'], output_type='df')
# print(mydata)
# print("===============================================================================================================")

# To get your data into a csv file
df = pd.DataFrame(mydata)
df
# path = r'python\EXAMPLES\Indicators\indicatorsHistoricalEx.csv'
# df.to_csv(path, index=False, header=True, sep='|')

# If you want the code into an html table format, you can use the example below in your html projects
# print(mydata.to_html())

HTTP Error 403: No Access to this feature.
None
===============================================================================================================

Empty DataFrame
Columns: []
Index: []