In [2]:
import pandas as pd
import tradingeconomics as te
te.login('guest:guest')

## Without a client key only a small sample of data will be given.

## Putting country name or indicator name in square brackets [] will result, by default
## in the dictionary type for several countries and indicators.
## EXE: country=['mexico', 'sweden']

## With no output_type defined, the result will be of the dictionary type.
## Use output_type='df' to display in pandas dataframe.

# To list the countries available.
mydata = te.getEurostatData(lists='countries', output_type='df')
print(mydata)
print("===============================================================================================================")

# To list the categories and category groups available.
mydata = te.getEurostatData(lists='categories', output_type='df')
print(mydata)
print("===============================================================================================================")

# to get Eurostat data by Category Group.
mydata = te.getEurostatData(category_group='Poverty', output_type='df')
print(mydata)
print("===============================================================================================================")

# To get Eurostat data by Category.
mydata = te.getEurostatData(category='People at risk of income poverty after social transfers', output_type='df')
print(mydata)
print("===============================================================================================================")

# To get Eurostat data by Country.
mydata = te.getEurostatData(country='Denmark', output_type='df')
print(mydata)
print("===============================================================================================================")

# To get Eurostat data by Country and category.
mydata = te.getEurostatData(country='Denmark', category='People at risk of income poverty after social transfers', output_type='df')
print(mydata)
print("===============================================================================================================")

# To get Eurostat data by Country and category group.
mydata = te.getEurostatData(country='Denmark', category_group='Poverty', output_type='df')
print(mydata)
print("===============================================================================================================")

# To get historical data by ID.
mydata = te.getHistoricalEurostat(ID='24804', output_type='df')
print(mydata)
print("===============================================================================================================")

# To get historical data by ID and a start date.
mydata = te.getHistoricalEurostat(
    ID='24804', initDate='2015-01-01', output_type='df')
print(mydata)
print("===============================================================================================================")

# To get historical data by ID and a date range.
mydata = te.getHistoricalEurostat(
    ID='24804', initDate='2015-01-01', endDate='2020-01-01', output_type='df')
print(mydata)
print("===============================================================================================================")

# To get your data into a csv file
df = pd.DataFrame(mydata)
path = r'eurostat.csv'
df.to_csv(path, index=False, header=True, sep='|')

# If you want the code into an html table format, you can use the example below in your html projects
# print(mydata.to_html())

           Country
0           Sweden
1            Spain
2         Slovenia
3         Slovakia
4          Romania
5         Portugal
6           Poland
7      Netherlands
8            Malta
9       Luxembourg
10       Lithuania
11          Latvia
12           Italy
13         Ireland
14         Hungary
15          Greece
16         Germany
17          France
18         Finland
19  European Union
20       Euro Area
21         Estonia
22         Denmark
23  Czech Republic
24          Cyprus
25         Croatia
26        Bulgaria
27         Belgium
28         Austria
===============================================================================================================
                                            Category      CategoryGroup
0                              Employment: Full-time         Employment
1  Employment and activity: Total employment (res...         Employment
2  Population and employment: Total employment do...  National accounts
===============================================================================================================
      ID         Country                                           Category  \
0  15375         Denmark  People at risk of income poverty after social ...
1  15373  Czech Republic  People at risk of income poverty after social ...
2  15371        Bulgaria  People at risk of income poverty after social ...

  CategoryGroup                                                URL Unit  \
0       Poverty  /denmark/people-at-risk-of-income-poverty-afte...    %
1       Poverty  /czech-republic/people-at-risk-of-income-pover...    %
2       Poverty  /bulgaria/people-at-risk-of-income-poverty-aft...    %

  Frequency  LatestValue      LatestValueDate  PreviousValue  \
0    Yearly         11.8  2023-12-31T00:00:00           12.4
1    Yearly          9.8  2023-12-31T00:00:00           10.2
2    Yearly         20.6  2023-12-31T00:00:00           22.9

     PreviousValueDate  FirstValue       FirstValueDate  HighestValue  \
0  2022-12-31T00:00:00        10.0  2001-12-31T00:00:00          13.3
1  2022-12-31T00:00:00         8.0  2001-12-31T00:00:00          10.4
2  2022-12-31T00:00:00        14.0  2000-12-31T00:00:00          23.8

      HighestValueDate  LowestValue      LowestValueDate           LastUpdate
0  2010-12-31T00:00:00         10.0  2001-12-31T00:00:00  2024-04-09T11:47:00
1  2005-12-31T00:00:00          8.0  2001-12-31T00:00:00  2024-04-09T11:47:00
2  2020-12-31T00:00:00         14.0  2002-12-31T00:00:00  2024-04-09T11:47:00
===============================================================================================================
      ID   Country                                           Category  \
0  15371  Bulgaria  People at risk of income poverty after social ...
1  15369   Belgium  People at risk of income poverty after social ...
2  15407   Austria  People at risk of income poverty after social ...

  CategoryGroup                                                URL Unit  \
0       Poverty  /bulgaria/people-at-risk-of-income-poverty-aft...    %
1       Poverty  /belgium/people-at-risk-of-income-poverty-afte...    %
2       Poverty  /austria/people-at-risk-of-income-poverty-afte...    %

  Frequency  LatestValue      LatestValueDate  PreviousValue  \
0    Yearly         20.6  2023-12-31T00:00:00           22.9
1    Yearly         12.3  2023-12-31T00:00:00           13.2
2    Yearly         14.8  2022-12-31T00:00:00           14.7

     PreviousValueDate  FirstValue       FirstValueDate  HighestValue  \
0  2022-12-31T00:00:00        14.0  2000-12-31T00:00:00          23.8
1  2022-12-31T00:00:00        13.0  2000-12-31T00:00:00          16.4
2  2021-12-31T00:00:00        12.0  2000-12-31T00:00:00          15.2

      HighestValueDate  LowestValue      LowestValueDate           LastUpdate
0  2020-12-31T00:00:00         14.0  2002-12-31T00:00:00  2024-04-09T11:47:00
1  2018-12-31T00:00:00         12.3  2023-12-31T00:00:00  2024-04-09T11:47:00
2  2008-12-31T00:00:00         12.0  2007-12-31T00:00:00  2024-04-09T11:47:00
===============================================================================================================
    ID  Country                                           Category  \
0  110  Denmark                              Employment: Full-time
1  109  Denmark  Population and employment: Total employment do...
2  108  Denmark                         Production in construction

                                  CategoryGroup  \
0                                    Employment
1                             National accounts
2  Construction, building and civil engineering

                                                 URL            Unit  \
0   /denmark/employment-full-time-eurostat-data.html        Thousand
1  /denmark/population-employment-total-employmen...               %
2  /denmark/production-in-construction-eurostat-d...  % year-on-year

   Frequency  LatestValue      LatestValueDate  PreviousValue  \
0  Quarterly       2184.9  2022-06-30T00:00:00         2160.8
1  Quarterly          0.0  2023-12-31T00:00:00            0.1
2    Monthly         -1.6  2024-02-29T00:00:00           -1.6

     PreviousValueDate  FirstValue       FirstValueDate  HighestValue  \
0  2022-03-31T00:00:00      2061.9  1998-06-30T00:00:00        2212.4
1  2023-09-30T00:00:00        -0.6  1995-06-30T00:00:00           2.1
2  2024-01-31T00:00:00         5.6  2001-01-31T00:00:00          30.5

      HighestValueDate  LowestValue      LowestValueDate           LastUpdate
0  2001-09-30T00:00:00       1896.3  2012-03-31T00:00:00  2024-03-22T15:16:00
1  2021-09-30T00:00:00         -2.6  2020-06-30T00:00:00  2024-04-20T11:44:00
2  2008-07-31T00:00:00        -17.2  2010-02-28T00:00:00  2024-04-21T11:35:00
===============================================================================================================
      ID  Country                                           Category  \
0  15375  Denmark  People at risk of income poverty after social ...

  CategoryGroup                                                URL Unit  \
0       Poverty  /denmark/people-at-risk-of-income-poverty-afte...    %

  Frequency  LatestValue      LatestValueDate  PreviousValue  \
0    Yearly         11.8  2023-12-31T00:00:00           12.4

     PreviousValueDate  FirstValue       FirstValueDate  HighestValue  \
0  2022-12-31T00:00:00        10.0  2001-12-31T00:00:00          13.3

      HighestValueDate  LowestValue      LowestValueDate           LastUpdate
0  2010-12-31T00:00:00         10.0  2001-12-31T00:00:00  2024-04-09T11:47:00
===============================================================================================================
      ID  Country                                           Category  \
0  15671  Denmark  Population living in a dwelling with a leaking...
1  15612  Denmark                    In work at Risk of Poverty rate
2  15375  Denmark  People at risk of income poverty after social ...

  CategoryGroup                                                URL Unit  \
0       Poverty  /denmark/population-living-in-a-dwelling-with-...    %
1       Poverty  /denmark/in-work-at-risk-of-poverty-rate-euros...    %
2       Poverty  /denmark/people-at-risk-of-income-poverty-afte...    %

  Frequency  LatestValue      LatestValueDate  PreviousValue  \
0    Yearly         16.8  2020-12-31T00:00:00           14.9
1    Yearly          6.0  2023-12-31T00:00:00            5.9
2    Yearly         11.8  2023-12-31T00:00:00           12.4

     PreviousValueDate  FirstValue       FirstValueDate  HighestValue  \
0  2019-12-31T00:00:00         8.2  2003-12-31T00:00:00          17.6
1  2022-12-31T00:00:00         4.5  2003-12-31T00:00:00           6.5
2  2022-12-31T00:00:00        10.0  2001-12-31T00:00:00          13.3

      HighestValueDate  LowestValue      LowestValueDate           LastUpdate
0  2012-12-31T00:00:00          7.8  2009-12-31T00:00:00  2024-03-22T15:16:00
1  2010-12-31T00:00:00          4.1  2007-12-31T00:00:00  2024-04-09T11:47:00
2  2010-12-31T00:00:00         10.0  2001-12-31T00:00:00  2024-04-09T11:47:00
===============================================================================================================
      ID                 Date  Value           LastUpdate
0  24804  2018-12-31T00:00:00    2.1  2020-07-02T17:46:00
1  24804  2019-12-31T00:00:00    1.8  2020-07-02T17:46:00
2  24804  2020-12-31T00:00:00    2.4  2021-04-20T23:16:00
===============================================================================================================
      ID                 Date  Value           LastUpdate
0  24804  2018-12-31T00:00:00    2.1  2020-07-02T17:46:00
1  24804  2019-12-31T00:00:00    1.8  2020-07-02T17:46:00
2  24804  2020-12-31T00:00:00    2.4  2021-04-20T23:16:00
===============================================================================================================
      ID                 Date  Value           LastUpdate
0  24804  2017-12-31T00:00:00    2.7  2020-07-02T17:46:00
1  24804  2018-12-31T00:00:00    2.1  2020-07-02T17:46:00
2  24804  2019-12-31T00:00:00    1.8  2020-07-02T17:46:00
===============================================================================================================